baseURL = "https://theinterdisciplinary.github.io/"
languageCode = "en-us"
title = "The Interdisciplinary"
theme = "PaperMod"

[params]
    env = "production"
    title = "The Interdisciplinary"
    description = "A Journal for Science, Philosophy and Society"
    # Das aktiviert das "Magazine"-Feeling auf der Startseite
    homeInfoParams = { Title = "The Interdisciplinary", Content = "Bridging the silos between academic fields." }

[menu]
    [[menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 10
